service: meishi

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  s3BucketName: "meishi-${self:provider.stage}-business-card-upload-bucket"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "textract:AnalyzeDocument"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::${self:custom.s3BucketName}"
  environment:
    S3_BUCKET_NAME: ${self:custom.s3BucketName}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  read-business-card:
    handler: bin/read-business-card
    events:
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*