service: meishi

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "arn:aws:logs:*:*:*"

custom:
  s3BucketName: "meishi-${self:provider.stage}-business-card-upload-bucket"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  read-business-card:
    handler: bin/read-business-card
    events:
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*