service: meishi

frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-pseudo-parameters

custom:
  dynamodbTableName: "meishi-${self:provider.stage}-business-card-table"
  s3BucketName: "meishi-${self:provider.stage}-business-card-upload-bucket"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "logs:DescribeLogStreams"
      Resource:
        - "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "comprehend:DetectEntities"
        - "textract:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodbTableName}
    - Effect: "Allow"
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${self:custom.s3BucketName}
        - arn:aws:s3:::${self:custom.s3BucketName}/*
  environment:
    S3_BUCKET_NAME: ${self:custom.s3BucketName}
    DYNAMODB_TABLE_NAME: ${self:custom.dynamodbTableName}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  read-business-card:
    handler: bin/read-business-card
    events:
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*

resources:
  Resources:

    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodbTableName}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
